// <auto-generated />
namespace TMCatalog.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DBchange3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBchange3));
        
        string IMigrationMetadata.Id
        {
            get { return "202005081914247_DBchange3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
